buffer_duration: 8.0
input: http://localhost:8000/output.mpd
min_rebuffer_duration: 2.0
min_start_duration: 2.0
mod_abr: dash
mod_analyzer:
- data_collector
mod_buffer: buffer_manager
mod_bw: bw_meter
mod_downloader: tcp
mod_scheduler: scheduler
panic_buffer_level: 2.5
run_dir: ./logs
safe_buffer_level: 6.0
time_factor: 1.0
verbose: true
